### ISSUE TITLE
Fix review script language bug

### ISSUE THREAD

**Issue by WillBeethoven** [WillBeethoven-Work/Review-Project-Assigner#1]
```python
|2017-10-11 16:14:23,467| Requesting certifications...
Traceback (most recent call last):
  File "will_beethoven.py", line 174, in <module>
    request_reviews(args.token)
  File "will_beethoven.py", line 105, in request_reviews
    project_language_pairs = fetch_certified_pairs()
  File "will_beethoven.py", line 87, in fetch_certified_pairs
    languages = me_resp.json()['application']['languages'] or ['en-us']
KeyError: 'application'
```

**Comment by WillBeethoven** [comment]
```JSON
{u'agreement_version': u'2017-08-01', u'mentor_languages': [u'zh_HANS', u'en'], u'name': u'Beethoven', u'github_token': u'f51d2aad53e69d7
f848946bc8d0aa34fa4b7369b', u'email': u'willbeethoven@gmail.com', u'preconditions_completed': True, u'role': u'grader', u'mentor_country_
code': u'CN', u'id': 31632, u'udacity_key': u'6207103575', u'accepted_terms': True}
```

**Comment by WillBeethoven** [comment]
Line 80: `languages = me_resp.json()['mentor_languages']`
