### ISSUE TITLE
Didn't assign project

### ISSUE THREAD

**Issue by WillBeethoven** [WillBeethoven-Work/Review-Project-Assigner#2]
```python
|2017-10-12 06:01:08,128| Creating a request for 42 possible project/language combinations
|2017-10-12 06:01:08,829| Creating a request for 42 possible project/language combinations
|2017-10-12 06:01:09,575| Creating a request for 42 possible project/language combinations
|2017-10-12 06:01:10,302| Creating a request for 42 possible project/language combinations

Traceback (most recent call last):
  File "/home/willbeethoven/will_beethoven.py", line 143, in <module>
    request_reviews(UDACITY_AUTH_TOKEN)
  File "/home/willbeethoven/will_beethoven.py", line 106, in request_reviews
    wait_for_assign_eligible()
  File "/home/willbeethoven/will_beethoven.py", line 58, in wait_for_assign_eligible
    if assigned_resp.status_code == 404 or assigned_resp.json()['assigned_count'] < 2:
  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 812, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/simplejson/__init__.py", line 516, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python2.7/dist-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/local/lib/python2.7/dist-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.scanner.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by WillBeethoven** [comment]
Documentation: https://review.udacity.com/public-api.html

**Comment by WillBeethoven** [comment]
## Possibility 1: The Ghost Project
![screen shot 2017-10-12 at 3 11 32 am](https://user-images.githubusercontent.com/14329786/31461181-4e5e8a58-aefb-11e7-9381-4b9fb928e89e.png)
![screen shot 2017-10-12 at 3 12 04 am](https://user-images.githubusercontent.com/14329786/31461182-4fa24eb8-aefb-11e7-9f57-a06498103388.png)

Ask help from @evestrom

**Comment by WillBeethoven** [comment]
It works when I try https://review.udacity.com/api-doc/index.html#!/submission_requests/post_submission_requests

It make me want to request the specific reveiw.

**Comment by WillBeethoven** [comment]
## Possibility 2: PythonAnywhere

Download the anaconda and try it locally.

**Comment by WillBeethoven** [comment]
# REAL REASON
Request too much!!!
When I only choose English projects, it works.

![screen shot 2017-10-14 at 4 04 49 am](https://user-images.githubusercontent.com/14329786/31564673-548a299a-b096-11e7-9712-c3857d7b2e97.png)

Thanks for @evestorm and @PoBlue

**Comment by WillBeethoven** [comment]
## Last test with PythonAnywhere

Gocha!
